# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jack/sources/basic_lisp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jack/sources/basic_lisp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jack/sources/basic_lisp/CMakeFiles /home/jack/sources/basic_lisp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jack/sources/basic_lisp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named basic_lisp

# Build rule for target.
basic_lisp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 basic_lisp
.PHONY : basic_lisp

# fast build rule for target.
basic_lisp/fast:
	$(MAKE) -f CMakeFiles/basic_lisp.dir/build.make CMakeFiles/basic_lisp.dir/build
.PHONY : basic_lisp/fast

src/builtins_base.o: src/builtins_base.c.o
.PHONY : src/builtins_base.o

# target to build an object file
src/builtins_base.c.o:
	$(MAKE) -f CMakeFiles/basic_lisp.dir/build.make CMakeFiles/basic_lisp.dir/src/builtins_base.c.o
.PHONY : src/builtins_base.c.o

src/builtins_base.i: src/builtins_base.c.i
.PHONY : src/builtins_base.i

# target to preprocess a source file
src/builtins_base.c.i:
	$(MAKE) -f CMakeFiles/basic_lisp.dir/build.make CMakeFiles/basic_lisp.dir/src/builtins_base.c.i
.PHONY : src/builtins_base.c.i

src/builtins_base.s: src/builtins_base.c.s
.PHONY : src/builtins_base.s

# target to generate assembly for a file
src/builtins_base.c.s:
	$(MAKE) -f CMakeFiles/basic_lisp.dir/build.make CMakeFiles/basic_lisp.dir/src/builtins_base.c.s
.PHONY : src/builtins_base.c.s

src/builtins_math.o: src/builtins_math.c.o
.PHONY : src/builtins_math.o

# target to build an object file
src/builtins_math.c.o:
	$(MAKE) -f CMakeFiles/basic_lisp.dir/build.make CMakeFiles/basic_lisp.dir/src/builtins_math.c.o
.PHONY : src/builtins_math.c.o

src/builtins_math.i: src/builtins_math.c.i
.PHONY : src/builtins_math.i

# target to preprocess a source file
src/builtins_math.c.i:
	$(MAKE) -f CMakeFiles/basic_lisp.dir/build.make CMakeFiles/basic_lisp.dir/src/builtins_math.c.i
.PHONY : src/builtins_math.c.i

src/builtins_math.s: src/builtins_math.c.s
.PHONY : src/builtins_math.s

# target to generate assembly for a file
src/builtins_math.c.s:
	$(MAKE) -f CMakeFiles/basic_lisp.dir/build.make CMakeFiles/basic_lisp.dir/src/builtins_math.c.s
.PHONY : src/builtins_math.c.s

src/eval.o: src/eval.c.o
.PHONY : src/eval.o

# target to build an object file
src/eval.c.o:
	$(MAKE) -f CMakeFiles/basic_lisp.dir/build.make CMakeFiles/basic_lisp.dir/src/eval.c.o
.PHONY : src/eval.c.o

src/eval.i: src/eval.c.i
.PHONY : src/eval.i

# target to preprocess a source file
src/eval.c.i:
	$(MAKE) -f CMakeFiles/basic_lisp.dir/build.make CMakeFiles/basic_lisp.dir/src/eval.c.i
.PHONY : src/eval.c.i

src/eval.s: src/eval.c.s
.PHONY : src/eval.s

# target to generate assembly for a file
src/eval.c.s:
	$(MAKE) -f CMakeFiles/basic_lisp.dir/build.make CMakeFiles/basic_lisp.dir/src/eval.c.s
.PHONY : src/eval.c.s

src/lisp.o: src/lisp.c.o
.PHONY : src/lisp.o

# target to build an object file
src/lisp.c.o:
	$(MAKE) -f CMakeFiles/basic_lisp.dir/build.make CMakeFiles/basic_lisp.dir/src/lisp.c.o
.PHONY : src/lisp.c.o

src/lisp.i: src/lisp.c.i
.PHONY : src/lisp.i

# target to preprocess a source file
src/lisp.c.i:
	$(MAKE) -f CMakeFiles/basic_lisp.dir/build.make CMakeFiles/basic_lisp.dir/src/lisp.c.i
.PHONY : src/lisp.c.i

src/lisp.s: src/lisp.c.s
.PHONY : src/lisp.s

# target to generate assembly for a file
src/lisp.c.s:
	$(MAKE) -f CMakeFiles/basic_lisp.dir/build.make CMakeFiles/basic_lisp.dir/src/lisp.c.s
.PHONY : src/lisp.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/basic_lisp.dir/build.make CMakeFiles/basic_lisp.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/basic_lisp.dir/build.make CMakeFiles/basic_lisp.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/basic_lisp.dir/build.make CMakeFiles/basic_lisp.dir/src/main.c.s
.PHONY : src/main.c.s

src/print.o: src/print.c.o
.PHONY : src/print.o

# target to build an object file
src/print.c.o:
	$(MAKE) -f CMakeFiles/basic_lisp.dir/build.make CMakeFiles/basic_lisp.dir/src/print.c.o
.PHONY : src/print.c.o

src/print.i: src/print.c.i
.PHONY : src/print.i

# target to preprocess a source file
src/print.c.i:
	$(MAKE) -f CMakeFiles/basic_lisp.dir/build.make CMakeFiles/basic_lisp.dir/src/print.c.i
.PHONY : src/print.c.i

src/print.s: src/print.c.s
.PHONY : src/print.s

# target to generate assembly for a file
src/print.c.s:
	$(MAKE) -f CMakeFiles/basic_lisp.dir/build.make CMakeFiles/basic_lisp.dir/src/print.c.s
.PHONY : src/print.c.s

src/reader.o: src/reader.c.o
.PHONY : src/reader.o

# target to build an object file
src/reader.c.o:
	$(MAKE) -f CMakeFiles/basic_lisp.dir/build.make CMakeFiles/basic_lisp.dir/src/reader.c.o
.PHONY : src/reader.c.o

src/reader.i: src/reader.c.i
.PHONY : src/reader.i

# target to preprocess a source file
src/reader.c.i:
	$(MAKE) -f CMakeFiles/basic_lisp.dir/build.make CMakeFiles/basic_lisp.dir/src/reader.c.i
.PHONY : src/reader.c.i

src/reader.s: src/reader.c.s
.PHONY : src/reader.s

# target to generate assembly for a file
src/reader.c.s:
	$(MAKE) -f CMakeFiles/basic_lisp.dir/build.make CMakeFiles/basic_lisp.dir/src/reader.c.s
.PHONY : src/reader.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... basic_lisp"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/builtins_base.o"
	@echo "... src/builtins_base.i"
	@echo "... src/builtins_base.s"
	@echo "... src/builtins_math.o"
	@echo "... src/builtins_math.i"
	@echo "... src/builtins_math.s"
	@echo "... src/eval.o"
	@echo "... src/eval.i"
	@echo "... src/eval.s"
	@echo "... src/lisp.o"
	@echo "... src/lisp.i"
	@echo "... src/lisp.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/print.o"
	@echo "... src/print.i"
	@echo "... src/print.s"
	@echo "... src/reader.o"
	@echo "... src/reader.i"
	@echo "... src/reader.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

